### ISSUE TITLE
Failed to get similar books: Failed to create driver...

### ISSUE THREAD

**Issue by Snuffy2** [TheWicklowWolf/eBookBuddy#4]
I've setup eBookBuddy using the Docker Compose below. It isn't showing any recommendations and is showing the errors in the logs below.

```
  ebookbuddy:
    depends_on:
      readarr_ebook:
        condition: service_healthy
    image: thewicklowwolf/ebookbuddy:latest
    container_name: ebookbuddy
    network_mode: service:vpn
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      TZ: $TZ
      readarr_address: http://vpn:8788
      readarr_api_key: <redacted>
      root_folder_path: /data/eBooks/Collection/
      auto_start: True
      search_for_missing_book: True
    volumes:
      - ${APPDATA}/ebookbuddy/config:/ebookbuddy/config
      - ${APPDATA}/ebookbuddy/gunicorn_config/gunicorn_config.py:/ebookbuddy/gunicorn_config.py
      - $LOCALTIME
    labels:
      - autoheal=true
      - traefik.enable=true
      - traefik.http.routers.ebookbuddy-int.priority=20
      - "traefik.http.routers.ebookbuddy-int.rule=Host(`ebookbuddy.$DOMAIN`) && $CLIENTIP_LOCAL_IPS"
      - traefik.http.routers.ebookbuddy-int.entrypoints=websecure_7443
      - traefik.http.routers.ebookbuddy-int.middlewares=chain-default@file
      - traefik.http.routers.ebookbuddy-int.service=ebookbuddy
      - traefik.http.routers.ebookbuddy-ext.priority=10
      - "traefik.http.routers.ebookbuddy-ext.rule=Host(`ebookbuddy.$DOMAIN`)"
      - traefik.http.routers.ebookbuddy-ext.entrypoints=websecure_7443
      - traefik.http.routers.ebookbuddy-ext.middlewares=chain-organizr-auth@file
      - traefik.http.routers.ebookbuddy-ext.service=ebookbuddy
      - traefik.http.services.ebookbuddy.loadbalancer.server.port=${EBOOKBUDDY_PORT}
```

```
ebookbuddy      | [2024-08-15 20:32:25 -0400] [1] [INFO] Starting gunicorn 22.0.0
ebookbuddy      | [2024-08-15 20:32:25 -0400] [1] [INFO] Listening at: http://0.0.0.0:5010 (1)
ebookbuddy      | [2024-08-15 20:32:25 -0400] [1] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
ebookbuddy      | [2024-08-15 20:32:25 -0400] [7] [INFO] Booting worker with pid: 7
ebookbuddy      | **************************************************
ebookbuddy      |
ebookbuddy      | eBookBuddy Version: 0.1.3
ebookbuddy      |
ebookbuddy      | **************************************************
ebookbuddy      | Loading Config via file
ebookbuddy      | 10.100.100.51 - - [2024-08-15 20:32:26] "GET /socket.io/?EIO=4&transport=polling&t=P5OcPba HTTP/1.1" 200 254 0.000736
ebookbuddy      | 10.100.100.51 - - [2024-08-15 20:32:27] "POST /socket.io/?EIO=4&transport=polling&t=P5OcPbv&sid=86i6qpDZRrTKv-NMAAAA HTTP/1.1" 200 201 0.003885
ebookbuddy      | 10.100.100.51 - - [2024-08-15 20:32:27] "GET /socket.io/?EIO=4&transport=polling&t=P5OcPbw&sid=86i6qpDZRrTKv-NMAAAA HTTP/1.1" 200 189 0.000203
ebookbuddy      | 10.100.100.51 - - [2024-08-15 20:32:27] "GET /socket.io/?EIO=4&transport=polling&t=P5OcPcZ&sid=86i6qpDZRrTKv-NMAAAA HTTP/1.1" 200 157 0.000154
ebookbuddy      | Getting Books from Readarr
ebookbuddy      | Searching for new books
ebookbuddy      | Creating New Driver...
ebookbuddy      | ====== WebDriver manager ======
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | There is no [linux64] geckodriver "v0.35.0" for browser firefox "128.0" in cache
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Getting latest mozilla release info for v0.35.0
ebookbuddy      | About to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
ebookbuddy      | Driver downloading response is 200
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Driver has been saved in cache [/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0]
ebookbuddy      | Failed to create driver: [Errno 8] Exec format error: '/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver'
ebookbuddy      | Failed to get similar books: Failed to create driver...
ebookbuddy      | Discovered 0 potential books
ebookbuddy      | Creating New Driver...
ebookbuddy      | ====== WebDriver manager ======
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Driver [/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
ebookbuddy      | Failed to create driver: [Errno 8] Exec format error: '/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver'
ebookbuddy      | Failed to get similar books: Failed to create driver...
ebookbuddy      | Discovered 0 potential books
ebookbuddy      | Creating New Driver...
ebookbuddy      | ====== WebDriver manager ======
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Driver [/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
ebookbuddy      | Failed to create driver: [Errno 8] Exec format error: '/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver'
ebookbuddy      | Failed to get similar books: Failed to create driver...
ebookbuddy      | Discovered 0 potential books
ebookbuddy      | Creating New Driver...
ebookbuddy      | ====== WebDriver manager ======
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Driver [/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
ebookbuddy      | Failed to create driver: [Errno 8] Exec format error: '/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver'
ebookbuddy      | Failed to get similar books: Failed to create driver...
ebookbuddy      | Discovered 0 potential books
ebookbuddy      | Creating New Driver...
ebookbuddy      | ====== WebDriver manager ======
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Driver [/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
ebookbuddy      | Failed to create driver: [Errno 8] Exec format error: '/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver'
ebookbuddy      | Failed to get similar books: Failed to create driver...
ebookbuddy      | Discovered 0 potential books
ebookbuddy      | Creating New Driver...
ebookbuddy      | ====== WebDriver manager ======
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Get LATEST geckodriver version for 128.0 firefox
ebookbuddy      | Driver [/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver] found in cache
ebookbuddy      | Failed to create driver: [Errno 8] Exec format error: '/home/general_user/.wdm/drivers/geckodriver/linux64/v0.35.0/geckodriver'
ebookbuddy      | Failed to get similar books: Failed to create driver...
ebookbuddy      | Discovered 0 potential books
ebookbuddy      | Search Exhausted - Try selecting more books from existing Readarr library
ebookbuddy      | Finished Searching
```
